server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8
################# mysql基础配置 #################
spring:
  datasource:
    name: young-001
    url: jdbc:mysql://localhost:3306/young
    username: root
    password: 123456
################# redis基础配置 #################
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    jedis: #redis线程池设置
      pool:
        max-idle: 10
        min-idle: 1
        max-active: 10
################# mysql基础配置 #################
mybatis:
  mapper-locations: classpath:top/oyoung/erp/mapper/*.xml

logging:
#  path: logs/
  level.root: info


management.endpoints.web.exposure.include: info, health,env





