server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8
################# mysql #################
spring:
  datasource:
    name: young-001
    url: jdbc:mysql://localhost:3306/
    username: root
    password: 123456
    schema:
      - "classpath:schema-init.sql"
################# flyway #################
  flyway:
    enabled: true
    baseline-on-migrate: true
    init-sqls:
    schemas:
      - demo
    locations: "classpath:db/migration/mysql"
################# redis #################
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    jedis: #redis线程池设置
      pool:
        max-idle: 10
        min-idle: 1
        max-active: 10

################# mybatis #################
mybatis:
  mapper-locations: classpath:db/mapper/*.xml
  type-aliases-package: top.oyoung.erp.entity

logging:
#  path: logs/
  level.root: info


management.endpoints.web.exposure.include: info, health,env






